-- 在 Supabase SQL Editor 中运行此文件
-- https://supabase.com/dashboard/project/sujhbmkrmonjrcbcpxqb/sql/new

CREATE TABLE IF NOT EXISTS needs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL DEFAULT '',
  category TEXT DEFAULT '其他',
  author TEXT DEFAULT '',
  summary TEXT DEFAULT '',
  thoughts TEXT DEFAULT '',
  resolved BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 开启 RLS 并允许公开访问
ALTER TABLE needs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public access" ON needs;
CREATE POLICY "Public access" ON needs
  FOR ALL USING (true) WITH CHECK (true);
